[NEST]

; Detector conditions
; DUMMY VALUES (defined in constructor instead)
drift_field_config = 300.
gas_field_config = 0.
elife_config = 0.
g1_config = 0.
temperature_config = 174.1
pressure_config = 1.79
num_pmts_config = 902
double_pe_fraction_config = 0.
g1_gas_config = 0.
s2Fano_config = 0.
spe_res_config = 0.38
spe_thr_config = 0.
spe_eff_config = 1.
; REAL VALUES
S1_noise_config = 0.
S2_noise_config = 0.

; Geometry parameters
; DUMMY VALUES (either redundant or overriden)
radius_config = 0.
z_topDrift_config = 0.
dt_min_config = 0.
dt_max_config = 0.
; REAL VALUES
gas_gap_config = 10. ; mm

; Analysis parameters
; DUMMY VALUES (either redundant or defined in constructor instead)
S1_min_config = 0.
S1_max_config = 0.
S2_min_config = 0.
S2_max_config = 0.
s2_thr_config = 0.
coin_level_config = 3


[80t]

; Geometry parameters
; radius_config = 146.775 ; cm
; z_topDrift_config = 0. ; cm
; z_top_config = 0. ; cm
; z_bottom_config = -389.7415 ; cm

radius_config = 145. ; cm
z_topDrift_config = 0. ; cm
z_top_config = 0. ; cm
z_bottom_config = -383. ; cm



[60t]
; 60t is the active volume
; The parameters below are that of the FV 
; Geometry parameters
; radius_config = 146.775 ; cm
; z_topDrift_config = 0. ; cm
; z_top_config = 0. ; cm
; z_bottom_config = -291.55 ; cm

radius_config = 145. ; cm
z_topDrift_config = 0. ; cm
z_top_config = 0. ; cm
z_bottom_config = -284. ; cm


[40t]

; Geometry parameters
radius_config = 145 ; cm
z_topDrift_config = 0. ; cm
z_top_config = 0. ; cm
z_bottom_config = -184. ; cm
