name: build

on: [push, pull_request]

jobs:
  test_flamedisx:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest wheel
        pip install -r requirements.txt
    - name: Install flamedisx
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pytest
    - name: Lint with flake8
      run: |
        flake8 --per-file-ignores="__init__.py:F401,F403" --max-line-length=120 --exclude "x1t_sr1.py, TFP_files" --count flamedisx
